#!/bin/bash

# This script can run commands on all nodes on the cluster: ./fornode <commands>

source load_cluster_env.sh

for node in ${ALL_IPADDR[@]}; do
  echo "=> $node"
  ssh -o StrictHostKeyChecking=no $node PATH=$PATH:/home/ubuntu/anaconda3/bin:/home/ubuntu/anaconda3/condabin, $@ &
done
wait
