#!/bin/bash

# This script can run commands on all nodes on the cluster: ./fornode <commands>

my_address=$(ifconfig | grep 'inet.*broadcast' | awk '{print $2}')

# get cluster info
worker_pubips=$(ray get-worker-ips ~/ray_bootstrap_config.yaml)
slaves=()
for s in $worker_pubips; do slaves+=($(ssh -o StrictHostKeyChecking=no $s ifconfig | grep 'inet.*broadcast' | awk '{print $2}')); done
all_nodes=($my_address ${slaves[@]})

for node in ${all_nodes[@]}; do
  echo "=> $node"
  ssh -o StrictHostKeyChecking=no $node 'PATH=$PATH:/home/ubuntu/anaconda3/bin;'; $@
done